// Trait tables transcribed from MorphMarket Morphpedia (morphmarket.com/morphpedia/),
// compiled 2026-08-10. 21 species, 633 traits.
//
// Row format: "Name|TYPE|yearDiscovered|rarity"
//   TYPE   R = recessive, ID = incomplete dominant, D = dominant, P = polygenic,
//          L = locality, PH = physical, O = other
//   year   free text as Morphpedia prints it ("1992", "1990s", "~1995", "At least 2008").
//          Empty when Morphpedia lists none.
//   rarity rarest | lower | average | higher | common. Empty when Morphpedia lists none.
//
// Morphpedia's own trait counts are asserted against these tables by the build script,
// so a dropped or duplicated row fails the build rather than silently shipping.

export const TYPE_CODES = {
  R: 'recessive',
  ID: 'incomplete_dominant',
  D: 'dominant',
  P: 'polygenic',
  L: 'locality',
  PH: 'physical',
  O: 'other',
};

export const RARITY_VALUES = ['rarest', 'lower', 'average', 'higher', 'common'];

export const SPECIES_TRAITS = {
  'ball-python': {
    displayName: 'Ball Pythons',
    expectedCount: 231,
    rows: [
      '210 Hypo|R||rarest',
      'Acid|ID|2014|higher',
      'Adder|D|2006|average',
      'AHI|D|2009|rarest',
      'Ajax|ID|2016|rarest',
      'Albino|R|1992|common',
      'Alloy|ID|2009|rarest',
      'Ambush|ID|2010|rarest',
      'Arcane|ID|2016|lower',
      'Arid|ID|2012|rarest',
      'Arroyo|ID|2010|average',
      'Ashen|D|2009|rarest',
      'Asphalt|ID|2009|common',
      'Astro|ID|2012|rarest',
      'Atomic|R|2011|rarest',
      'Axanthic (GCR)|R|2010|higher',
      'Axanthic (Jolliff)|R|1997|rarest',
      'Axanthic (MJ)|R|2008|higher',
      'Axanthic (TSK)|R|1999|common',
      'Axanthic (VPI)|R|1997|common',
      'Bald|ID|2008|rarest',
      'Bambino|ID|2019|lower',
      'Bamboo|ID|2013|higher',
      'Banana|ID|2003|common',
      'Bang|ID|2014|higher',
      'Bengal|R||lower',
      'Black Axanthic|R|2008|higher',
      'Black Belly|D||rarest',
      'Black Head|ID|2002|common',
      'Black Lace|R||lower',
      'Black Pastel|ID|2002|common',
      'Blade|ID|2002|higher',
      'Bongo|ID|2012|higher',
      'Brown Back|P||rarest',
      'Butter|ID|2001|common',
      'Cafe|ID|2013|lower',
      'Calico|ID|2002|common',
      'Candy|R|2008|higher',
      'Caramel Albino|R|1996|average',
      'Carbon|ID||lower',
      'Carnivore|ID|2016|lower',
      'Champagne|ID|2005|higher',
      'Chino|ID|2013|rarest',
      'Chocolate|ID|1999|common',
      'Cinder|ID|2008|average',
      'Cinnamon|ID|2002|rarest',
      'Circle|ID||rarest',
      'Citron|ID|2012|lower',
      'Clown|R|1999|common',
      'Coffee|ID|2012|rarest',
      'Confusion|D|2012|higher',
      'Congo|D||rarest',
      'Copper|ID||lower',
      'Creed|ID||rarest',
      'Cryptic|R||common',
      'Cypress|ID|2012|common',
      'Dark Angel|ID|2017|rarest',
      'Dark Viking|ID|2013|rarest',
      'Desert|D||rarest',
      'Desert Ghost|R|2003|common',
      'Diesel|ID|2000s|rarest',
      'Dinker|O||higher',
      'Disco|ID|2004|higher',
      'Dot|ID|2009|rarest',
      'EMG|ID||rarest',
      'Enchi|ID|2002|common',
      'Enhancer|R|2004|higher',
      'Epic|ID||rarest',
      'Eramosa|D|2008|average',
      'Exo-lbb|ID|2006|rarest',
      'Fader|P||lower',
      'Fire|ID|2003-2005|common',
      'Flame|ID||average',
      'FNR Vanilla|ID|2008|rarest',
      'Frost|D|2011|rarest',
      'Furrow|ID|2014|average',
      'Fusion|ID|2016|lower',
      'Gaia|ID|2012|lower',
      'Gallium|ID|2009|rarest',
      'Genetic Black Back|P||rarest',
      'Genetic Reduced|P||rarest',
      'Genetic Stripe|R|1999|common',
      'GeneX|ID|2015|higher',
      'GHI|ID|2007|common',
      'Ghost (Vesper)|R|2000s|lower',
      'Glossy|ID|2012|rarest',
      'Gobi|ID|2012|rarest',
      'Gold Blush|D||lower',
      'Granite|ID|2003|average',
      'Gravel|ID|2006|common',
      'Grim|ID|2016|higher',
      'Harlequin|D||rarest',
      'Het Daddy|D||lower',
      'Het Red Axanthic|ID|2001|rarest',
      'Hidden Gene Woma|ID|1999|higher',
      'Hieroglyphic|ID||rarest',
      'High Intensity OD|ID|2010|higher',
      'High Orange Gene|ID|2021|rarest',
      'Honey|ID||average',
      'Huffman|ID||average',
      'Hybrid|O||lower',
      'Hydra|ID|2013|lower',
      'Hypo|R|1994|rarest',
      'Jaguar|ID||higher',
      'Java|ID|2011|lower',
      'Jedi|ID|2006|average',
      'Jolliff Tiger|ID||lower',
      'Jolt|ID||lower',
      'Joppa|ID|2009|lower',
      'Josie|D|2008|rarest',
      'Jungle Woma|ID|2005|average',
      'Kosmos|ID|2012|average',
      'KRG|ID|2013|lower',
      'Lace|ID|2002|common',
      'Lavender Albino|R|2001|common',
      'LC Black Magic|ID|2010|lower',
      'Lemonback|ID|2008|lower',
      'Leopard|D|2005|rarest',
      'Lesser|ID|2001|rarest',
      'Mahogany|ID|2005|common',
      'Maple|R|2019|lower',
      'Mario|ID|2012|average',
      'Marvel|ID||average',
      'Mckenzie|ID||average',
      'Melt|ID||rarest',
      'Metal Flake|R|2004|average',
      'Microscale|ID||rarest',
      'Migraine|R|2016|lower',
      'Mocha|ID||average',
      'Mojave|ID|2000|common',
      'Monarch|R|2009|higher',
      'Monsoon|R|2013|common',
      'Moray|R|2017|lower',
      'Mordor|D||rarest',
      'Mosaic|ID|2015|rarest',
      'Motley|ID||rarest',
      'Mystic|ID|2005|higher',
      'Nanny|ID|2011|average',
      'Nico|ID|2013|average',
      'Normal|O|~70 million years ago|higher',
      'Nova|D|2010|rarest',
      'Nr Mandarin|ID||higher',
      'Nyala|ID|2013|average',
      'Odium|ID||average',
      'OFY|ID|2009|rarest',
      'Orange Crush|R|2008|average',
      'Orange Dream|ID|2004|common',
      'Orange Ghost|R||higher',
      'Orbit|ID|2013|lower',
      'Oriole|D|2014|rarest',
      'Paint|R|2008|common',
      'Panther|ID|2004|lower',
      'Paradox|O||higher',
      'Pastel|ID|1994|common',
      'Patternless|R|2002|rarest',
      'Peach|ID|2007|average',
      'Phantom|ID|2005|higher',
      'Phenomenon|ID|2013|rarest',
      'Piebald|R|1997|common',
      'Pinstripe|D|2001|rarest',
      'Pixel|ID|2016|average',
      'Puzzle|R|2011|common',
      'Quake|ID|2012|lower',
      'Rain|ID||lower',
      'Rainbow|R|2015|higher',
      'RAR|ID|2017|rarest',
      'Raven|ID|2011|lower',
      'Razor|ID||average',
      'Reaper|ID|2009|rarest',
      'RECO|O|2011|rarest',
      'Red Gene|ID|2010|higher',
      'Red Stripe|ID||common',
      'Redhead|D|2013|higher',
      'Rhino|ID|2017|rarest',
      'Ringer|O||average',
      'Ringer Mark|O||',
      'Russo|ID|1998|higher',
      'Saar|ID|2016|rarest',
      'Sable|ID|2002|average',
      'Sahara|R||rarest',
      'Sandblast|ID|2010|higher',
      'Sandstorm|R|2019|rarest',
      'Sapphire|ID|2009|lower',
      'Satin|ID||rarest',
      'Scaleless Head|ID|2010|higher',
      'Scrambler|ID|2014|higher',
      'Shadow|ID|2014|lower',
      'Shatter|D||lower',
      'Sherg|ID|2010|rarest',
      'Shrapnel|ID||average',
      'Shredder|ID|2010|lower',
      'Smuggler|ID|2014|average',
      'Spark|ID||higher',
      'Special|ID||common',
      'Specter|ID||higher',
      'Spider|ID|1999|common',
      'Splash|D|2007|rarest',
      'Splatter|ID||rarest',
      'Spotnose|ID|2001|common',
      'Static|D|2008|lower',
      'Stranger|ID|2012|common',
      'Striker|ID|2016|average',
      'Sulfur|ID||average',
      'Sunrise|D|2010|rarest',
      'Sunset|R|2012|common',
      'Surge|ID||rarest',
      'Taronja|ID||rarest',
      'The Darkling|ID|2014|rarest',
      'Tornado|R|2019|rarest',
      'Tri-stripe|R||higher',
      'Trick|ID|2006|higher',
      'Trident|ID|2012|lower',
      'Trojan|ID||average',
      'Twister|ID||average',
      'Typhoon|D|2008|rarest',
      'Ultramel|R|~1995|common',
      'Vanilla|ID||common',
      'Vesper|D|1995|rarest',
      'Volta|L||lower',
      'Vudoo|ID|2018|average',
      'Web|ID||rarest',
      'Whitewash|R|2008|rarest',
      'Woma|ID|2000|average',
      'Wookie|ID|2013|higher',
      'Wrecking Ball|ID|2010|rarest',
      'X-treme Gene|ID|2009|average',
      'X-tremist|ID|2013|average',
      'Yellow Belly|ID|1999|common',
      'Zebra|R|2015|higher',
      'Zip Belly|D|2017|rarest',
      'Zuwadi|ID|2016|rarest',
    ],
  },

  'leopard-gecko': {
    displayName: 'Leopard Geckos',
    expectedCount: 63,
    rows: [
      'Abyssinian|P|2005|rarest',
      'Afghan Tangerine|P||lower',
      'Albino (Bell)|R||common',
      'Albino (Rainwater)|R|1998|higher',
      'Albino (Tremper)|R|1996|common',
      'Atomic|P||average',
      'BAE|R||average',
      'Baldy|P||lower',
      'Bandit|P|1995|higher',
      'Black Night|P||common',
      'Black Pearl|P||higher',
      'Blizzard|R|1995|common',
      'Blood|P|2002|common',
      'Blood Emerine|P||average',
      'Bold|P||common',
      'Bold Stripe|P||higher',
      'Carrot Head|P|2002|rarest',
      'Carrot Tail|P||average',
      'Cipher|R|2015|higher',
      'Clown|P|2012|common',
      'Eclipse|R|2004|common',
      'Electric|P||average',
      'Emerine|P|2004|higher',
      'Enigma|D|2006|rarest',
      'Extreme Bold|P||lower',
      'Firebold|P||common',
      'G Project|P|2006|average',
      'Ggg|P||lower',
      'Ghost|D||lower',
      'Giant|ID|2000|higher',
      'Glow Madness|P||rarest',
      'Green & Tangerine|P||',
      'Halloween|P|1990s|average',
      'High Yellow|P||rarest',
      'Hyper Xanthic|P|2002|higher',
      'Hypo|P||average',
      'Inferno|P||higher',
      'Jungle|P|1991|average',
      'Lavender|P|2003|higher',
      'Lemon Frost|ID|2012-2013|rarest',
      'Marble Eye|R|2006|lower',
      'Murphy Patternless|R|1991|higher',
      'NDBE|R|2013|lower',
      'Nieves Tangerine|P|1990s|rarest',
      'Normal|O||lower',
      'Pacific Green|P||lower',
      'Paradox|O||rarest',
      'Pastel|D|2014|rarest',
      'Patternless Stripe|P||rarest',
      'Purple Head|P|2010|average',
      'Rainbow Stripe|P||lower',
      'Red Stripe|P||higher',
      'Reverse Stripe|P||average',
      'Snake Eyes|P||rarest',
      'Snow (Gem)|D||average',
      'Snow (LBS)|P|1998|rarest',
      'Snow (Mack)|ID||common',
      'Snow (Tug)|D||rarest',
      'Super Hypo|P||higher',
      'Tangerine|P||common',
      'Tangerine Tornado|P||average',
      'Tango Crush|P|2018|lower',
      'White & Yellow|D|1996|',
    ],
  },

  'crested-gecko': {
    displayName: 'Crested Geckos',
    expectedCount: 55,
    rows: [
      'Axanthic|R||higher',
      'Bi-color|P||lower',
      'Black Base|D||higher',
      'Blushing|O||average',
      'Brindle|O||higher',
      'Buckskin|O||rarest',
      'Cappuccino|ID|2020|higher',
      'Chevron|P||rarest',
      'Cluster Spots|P||lower',
      'Cold Fusion|P||rarest',
      'Cream|P||common',
      'Creamsicle|P||lower',
      'Crowned|P||average',
      'Dalmatian|D||common',
      'Drippy|P||common',
      'Empty Back|ID|At least 2008|common',
      'Extreme Harlequin|P||common',
      'Flame|P|At least 1995|average',
      'Fringing|O||average',
      'Furred|P||lower',
      'Halloween|P||average',
      'Harlequin|P||common',
      'Hybrid|O||rarest',
      'Hypo|D||average',
      'Ink Spot|P||higher',
      'Kneecaps|P||average',
      'Lavender|P||higher',
      'Lilly White|ID|2010|common',
      'Monochrome|ID||rarest',
      'Normal|O|1994|rarest',
      'Obscurial Axanthic|R|2018|rarest',
      'Oil Spot|P||average',
      'Olive|P||lower',
      'Orange|P||higher',
      'Orange Patterning|D||higher',
      'Patternless|R||lower',
      'Phantom|R||lower',
      'Pinstripe|D||common',
      'Portholes|P||common',
      'Quad-stripe|P||higher',
      'Red Base|R||common',
      'Sable|ID|2017|average',
      'Snowflake|ID||higher',
      'Soft Scale|ID|2004|higher',
      'Solid Back|P||lower',
      'Super Dalmatian|D||higher',
      'Super Stripe|R||average',
      'Tailless|PH||lower',
      'Tangerine|ID|2005|higher',
      'Tiger|D||higher',
      'Tri-color|P||common',
      'White Patterning|D||higher',
      'White Tip|P||lower',
      'White Wall|ID||common',
      'Yellow Base|D||higher',
    ],
  },

  'boa-constrictor': {
    displayName: 'Boa Constrictors',
    expectedCount: 36,
    rows: [
      'Albino (Argentine)|R||rarest',
      'Albino (BWC)|R|1986|rarest',
      'Albino (Kahl)|R|1992|higher',
      'Albino (Prodigy)|R|2006|rarest',
      'Albino (Sharp)|R|1990s|higher',
      'Albino (VPI)|R||common',
      'Anerythristic (Carbon)|R|2015|rarest',
      'Anerythristic (RDR Black Eye)|R|2001|higher',
      'Anerythristic (Type 1)|R||rarest',
      'Anerythristic (Type 2)|R||rarest',
      'Arabesque|D|1989|rarest',
      'Aztec|ID||rarest',
      'Blood|R||higher',
      'Coral Albino|P|1992|rarest',
      'Fire|ID||higher',
      'Harlequin|ID||rarest',
      'Hypo|ID||common',
      'IMG|D|2007|rarest',
      'Inca|D||rarest',
      'Indy|D|2012|rarest',
      'Jaguar (Colombian)|ID||rarest',
      'Jungle|ID||higher',
      'Key West|ID||rarest',
      'Kubsch Pastel|P||higher',
      'Leopard|R||common',
      'Motley (Central American)|ID||rarest',
      'Motley (Colombian)|ID||rarest',
      'Normal|O||rarest',
      'Onyx|ID|2008|rarest',
      'Paradox|O||rarest',
      'PK Stripe|R|1991|rarest',
      'Raptor|ID||higher',
      'Roswell Laddertail|ID|2003|rarest',
      'Salmon Hypo|P|1990s|rarest',
      'Square Tail|R||rarest',
      'Sterling|R|2010|rarest',
    ],
  },

  'corn-snake': {
    displayName: 'Corn Snakes',
    expectedCount: 35,
    rows: [
      'Amelanistic|R|1959|common',
      'Anerythristic|R|1975|common',
      'Buf|D|2001|lower',
      'Caramel|R|1991|common',
      'Charcoal|R|1984|average',
      'Christmas|R||rarest',
      'Cinder|R|2000s|higher',
      'Diffused|R|1970s|common',
      'Dilute|R|1996|lower',
      'Halo|ID||average',
      'Hybrid|O||rarest',
      'Hypomelanistic|R|1980s|common',
      'Kastanie|R||average',
      'Lava|R|1994|average',
      'Lavender|R|1985|higher',
      'Masque|ID||average',
      'Miami|L||higher',
      'Microscale|R|2010|average',
      'Motley|R|1980s|common',
      'Normal|O||lower',
      'Palmetto|ID|2012|',
      'Paradox|O||rarest',
      'Peach|ID||rarest',
      'Pied Sided|O|1990s|average',
      'Red Factor|ID||common',
      'Scaleless|R||higher',
      'Stargazer|R|1990s|rarest',
      'Strawberry|R||average',
      'Stripe|R||higher',
      'Sunkissed|R|1990s|common',
      'Tequila Sunrise|P|2000s|rarest',
      'Terrazzo|R|Early 1990s|lower',
      'Tessera|D|2008|common',
      'Ultra|R|2001|higher',
      'Zigzag|P|1984|lower',
    ],
  },

  'gargoyle-gecko': {
    displayName: 'Gargoyle Geckos',
    expectedCount: 33,
    rows: [
      'Aberrant Stripe|P||higher',
      'Alterna|P||rarest',
      'Bacon|P|2014|common',
      'Banded|P||average',
      'Blue Eye|P||rarest',
      'Blush|P||average',
      'Brown Base|P||higher',
      'Dorsal Blotch|P||higher',
      'Exaggerated Horns|P||rarest',
      'Eyebrows|P||average',
      'Ghost|P||rarest',
      'Lipstick|P||lower',
      'Mosaic|P||rarest',
      'Mottled|P||rarest',
      'Orange|P||common',
      'Orange Base|P||lower',
      'Orange Spectacle|P||lower',
      'Pastel|P||lower',
      'Phantom Eye|P||lower',
      'Pink Base|P||average',
      'Red|P||common',
      'Red Base|P||common',
      'Red Spectacle|P||rarest',
      'Reticulated|P||common',
      'Skeleton|P||average',
      'Stripe|P||common',
      'Super Blotch|P||common',
      'Super Stripe|P||higher',
      'White|P||lower',
      'White Base|P||higher',
      'Yellow|P||lower',
      'Yellow Base|P||average',
      'Yellow Spectacle|P||average',
    ],
  },

  'reticulated-python': {
    displayName: 'Reticulated Pythons',
    expectedCount: 30,
    rows: [
      'Albino|R|1993|',
      'Albino (Purple Phase)|R|1993|common',
      'Albino (White Phase)|R|1993|common',
      'Amelanistic|R||rarest',
      'Anerythristic|R|2007|common',
      'Anthrax|R||common',
      'Bacan|ID|2014|average',
      'Bali|L||lower',
      'Blonde Albino|R||lower',
      'Caramel Albino|R||higher',
      'Genetic Stripe|R||higher',
      'Golden Child|ID||common',
      'Hybrid|O||rarest',
      'Indo Caramel Albino|R||',
      'Jaguar|ID||higher',
      'Jampea (Dwarf)|L||higher',
      'Kalaotoa (Super Dwarf)|L||common',
      'Kayuadi (Super Dwarf)|L||lower',
      'Motley|ID||common',
      'Normal|O||average',
      'Orange Ghost Stripe|R|2008|common',
      'Paradox|O||lower',
      'Phantom|ID||common',
      'Pied|R|2011|higher',
      'Platinum (Ultra)|ID||rarest',
      'Selayer (Dwarf)|L||average',
      'Sulawesi|L||lower',
      'Sunfire|ID||common',
      'Tiger|ID|1993|common',
      'Titanium|R||average',
    ],
  },

  'leachianus-gecko': {
    displayName: 'Leachianus Geckos',
    expectedCount: 17,
    rows: [
      'Bayonnaise|L||higher',
      'Brosse|L||higher',
      'Caanawa|L||average',
      'Conley Dark Morph|P||average',
      'Friedel (Mt Koghis)|P||lower',
      'GT Type A|O||common',
      'GT Type B|O||average',
      'GT Type C|O|1988|higher',
      'Isle Of Pines|L||common',
      'Moro|L||common',
      'Mt Humboldt|L||lower',
      'Mt Koghis|L||common',
      'Nuu Ami|L||common',
      'Nuu Ana|L||common',
      'Poindimie|L||higher',
      'Troger (Mt Koghis)|P||average',
      'Yate|L||common',
    ],
  },

  'bearded-dragon': {
    displayName: 'Bearded Dragons',
    expectedCount: 16,
    rows: [
      'Brown/tan/sand|P||',
      'Dunner|D||rarest',
      'Genetic Stripe|D||rarest',
      'Hypo|R||rarest',
      'Leatherback|ID||rarest',
      'Normal|O||rarest',
      'Orange|P||rarest',
      'Paradox|O||rarest',
      'Purple/blue|P||',
      'Recessive Leatherback|R|2004|rarest',
      'Red|P||rarest',
      'Translucent|R||rarest',
      'White|P||rarest',
      'Witblits|R||rarest',
      'Yellow/citrus|P||',
      'Zero|R||rarest',
    ],
  },

  'kingsnake': {
    displayName: 'Kingsnakes',
    expectedCount: 16,
    rows: [
      'Amelanistic|R||rarest',
      'Anerythristic|R||rarest',
      'Axanthic|R|1990s|rarest',
      'Corwin Hypo|O||rarest',
      'Erythristic|R||rarest',
      'Hyperxanthic|R||rarest',
      'Hypo|R||rarest',
      'Lavender Albino|R||rarest',
      'Long Beach Hypermelanistic|ID||rarest',
      'Mosaic|R|1997|rarest',
      'New England Axanthic|P||rarest',
      'Peanut Butter|R||rarest',
      'Sulfur|P||rarest',
      'White Brooks|R|1997|rarest',
      'White Sided|R|2000|rarest',
      'Whittier Mud|R||rarest',
    ],
  },

  'african-fat-tailed-gecko': {
    displayName: 'African Fat-Tailed Geckos',
    expectedCount: 12,
    rows: [
      'Amelanistic|R||common',
      'Caramel|R||average',
      'Ghost|R|2008|lower',
      'Jungle|P||rarest',
      'Normal|O||lower',
      'Oreo|R||common',
      'Patternless|R||common',
      'Stinger|R||rarest',
      'Stripe|D||higher',
      'Whiteout|ID||higher',
      'Zero|R||rarest',
      'Zulu|R||higher',
    ],
  },

  'carpet-python': {
    displayName: 'Carpet Pythons',
    expectedCount: 11,
    rows: [
      'Albino|R||rarest',
      'Axanthic|R||rarest',
      'Caramel|ID||rarest',
      'Granite|R|2001|rarest',
      'Hypo|ID|2010s|rarest',
      'Jaguar|ID|1997|rarest',
      'Normal|O||rarest',
      'Paradox|O||rarest',
      'Red Coastal|P||rarest',
      'Tiger|P|2000s|rarest',
      'Zebra|ID||rarest',
    ],
  },

  'hognose-snake': {
    displayName: 'Hognose Snakes',
    expectedCount: 11,
    rows: [
      'Albino|R|1992|rarest',
      'Arctic|ID|2000s|rarest',
      'Axanthic|R|1990|rarest',
      'Caramel|R|2001|rarest',
      'Conda|ID|2004|rarest',
      'Evans Hypo|R||rarest',
      'Lavender|R|2005|rarest',
      'Lemon Hypo|P||rarest',
      'Normal|O|10.3 million years ago|rarest',
      'RBE Pastel|P||rarest',
      'Shadow|P||rarest',
    ],
  },

  'rainbow-boa': {
    displayName: 'Rainbow Boas',
    expectedCount: 11,
    rows: [
      'Albino (Caramel)|R||rarest',
      'Albino (Outback)|R|2014|rarest',
      'Anery (Seib)|O||rarest',
      'Anery (Sharp)|R||rarest',
      'Bulls Eye|O||rarest',
      'Calico|R|2008|rarest',
      'Candy Stripe|ID|2011|rarest',
      'Hypo (Lockwood)|R|1994|rarest',
      'Pied|R|2013|rarest',
      'Pinstripe|R||rarest',
      'Wipeout|O||rarest',
    ],
  },

  'axolotl': {
    displayName: 'Axolotls',
    expectedCount: 11,
    rows: [
      'Axanthic|R||average',
      'Copper|R||common',
      'Dirty Leucistic|P||average',
      'Gfp|ID||higher',
      'Golden Albino|R||higher',
      'High Iridophores|P||lower',
      'Leucistic|R||common',
      'Melanoid|R|1961|common',
      'Melanoid Albino|R||common',
      'Normal|O||higher',
      'White|R||',
    ],
  },

  'burmese-python': {
    displayName: 'Burmese Pythons',
    expectedCount: 10,
    rows: [
      'Albino|R|1986|common',
      'Dwarf|O||rarest',
      'Enigma|O|2016|rarest',
      'Granite|R|1996|higher',
      'Hybrid|O|At least 2007|rarest',
      'Hypo|ID|2006|average',
      'Labyrinth|R||average',
      'Paradox|O||rarest',
      'Patternless|R|1987|common',
      'Piebald|R|2018|higher',
    ],
  },

  'green-tree-python': {
    displayName: 'Green Tree Pythons',
    expectedCount: 10,
    rows: [
      'Aru|O||higher',
      'Biak|O||common',
      'Calico|P||lower',
      'High Blue|P|1988|higher',
      'Jayapura|O||higher',
      'Kofiau|O|1996|lower',
      'Lereh|O||lower',
      'Manokwari|O||common',
      'Sorong|L||higher',
      'Wamena|L||average',
    ],
  },

  'short-tailed-python': {
    displayName: 'Short-Tailed Pythons',
    expectedCount: 7,
    rows: [
      'Albino (T+)|R||rarest',
      'Albino (T-) (Blood)|R||',
      'Batik|ID||rarest',
      'Caramel Albino (VPI)|ID||rarest',
      'Golden Eye|ID||rarest',
      'Matrix|ID||rarest',
      'Pollen|ID|2018|rarest',
    ],
  },

  'milk-snake': {
    displayName: 'Milk Snakes',
    expectedCount: 7,
    rows: [
      'Albino|R|1995|rarest',
      'Anerythristic|R||rarest',
      'Hypo|R|1993|rarest',
      'Normal|O||rarest',
      'Paradox|O||rarest',
      'Striped|O||rarest',
      'Tangerine|P||rarest',
    ],
  },

  'sand-boa': {
    displayName: 'Sand Boas',
    expectedCount: 6,
    rows: [
      'Albino|R||rarest',
      'Anery|R||rarest',
      'Dodoma|L||rarest',
      'Gene X|R||rarest',
      'Paradox Albino|R||rarest',
      'Stripe|D||rarest',
    ],
  },

  'chahoua-gecko': {
    displayName: 'Chahoua Geckos',
    expectedCount: 5,
    rows: [
      'High White|P||common',
      'Normal|O|1980s|rarest',
      'Pine Island|L||common',
      'White Collar|P||common',
      'White Shoulder|P||higher',
    ],
  },
};

export const TOTAL_EXPECTED_TRAITS = 633;
