// The gene database for the ACTIVE species. Gene tables are generated by
// scripts/species/buildSpeciesDatabase.mjs -- do not hand-edit them. The curated ball
// python source lives at scripts/species/sources/ballPythonCurated.json; edit that and
// rebuild. These generated tables are the app's ONLY gene data, so nothing can drift.
//
// Ball python is imported statically rather than through the registry because it is the
// default species: the app has to boot with a working gene database before anything has
// had a chance to await a species load. Every other species arrives via setActiveSpecies.
import ballPythonJson from '../config/species/ball-python.json';
import {
  DEFAULT_SPECIES_ID,
  getSpeciesById,
  loadSpeciesGeneTable,
  resolveSpeciesId,
} from './speciesRegistry';

// 'locality', 'physical' and 'other' come from Morphpedia's own classification. They were
// previously collapsed into 'polygenic', which mislabelled Normal, Hybrid, Paradox and a
// locality (Volta) as quantitative traits -- punnett.ts skips polygenic as non-Mendelian,
// so anything wrongly filed there was silently dropped from cross predictions.
export type GeneType =
  | 'recessive'
  | 'incomplete_dominant'
  | 'dominant'
  | 'polygenic'
  | 'locality'
  | 'physical'
  | 'other';

export type HealthFlag = 'wobble' | 'lethal_super' | 'infertility' | 'kinking';

export type GeneRecord = {
  geneName: string;
  geneType: GeneType;
  complex: string | null;
  hasSuperForm: boolean;
  superGeneName: string | null;
  aliases: string[];
  shorthand: string[];
  healthFlags: HealthFlag[];
  /**
   * Trade names that are the SAME allele as this gene, which a keeper may legitimately
   * choose as their label -- Trick / Hurricane / Blitz. Distinct from `aliases`: an alias
   * is a spelling that collapses onto the canonical name, whereas an equivalent name is
   * kept as typed. Genetics must still treat them as ONE gene; only the label differs.
   */
  equivalentNames?: string[];
  /** Free text as Morphpedia prints it -- "1992", "1990s", "~1995". Null when unlisted. */
  yearDiscovered?: string | null;
  /** rarest | lower | average | higher | common. Null when unlisted. */
  rarity?: string | null;
  notes?: string;
};

export type GeneAliasRow = {
  geneName: string;
  aliases: string[];
  shorthand: string[];
};

export type GeneGroups = {
  recessiveGenes: string[];
  incompleteDominantGenes: string[];
  dominantGenes: string[];
  polygenicGenes?: string[];
  localityGenes?: string[];
  physicalGenes?: string[];
  otherGenes?: string[];
  belComplexGenes: string[];
  blkELComplexGenes?: string[];
  spiderComplexGenes?: string[];
  eightBallComplexGenes?: string[];
  mahoganyComplexGenes?: string[];
  superStripeComplexGenes?: string[];
  axanthicLines?: string[];
  acidComplexGenes?: string[];
  clownComplexGenes?: string[];
  wobbleGenes?: string[];
  lethalSuperGenes?: string[];
  yellowBellyComplexGenes?: string[];
  patternModifierGenes?: string[];
  colorEnhancerGenes?: string[];
  darkeningGenes?: string[];
  stripeLinePatternGenes?: string[];
};

export type SpeciesGeneticsDatabase = {
  version: number;
  generatedAt: string;
  genes: GeneRecord[];
  groups: GeneGroups;
};

type RawGeneRecord = Omit<GeneRecord, 'aliases' | 'shorthand' | 'healthFlags'> & {
  aliases?: string[];
  shorthand?: string[];
  healthFlags?: string[];
};

type RawDatabase = Omit<SpeciesGeneticsDatabase, 'genes'> & {
  genes: RawGeneRecord[];
};

const DEFAULT_GENE_ALIAS_PRESETS: Record<string, { aliases?: string[]; shorthand?: string[] }> = {
  'pastel': { aliases: ['Pastel'], shorthand: ['PS', 'P'] },
  'super pastel': { aliases: ['Super Pastel'], shorthand: ['SPS'] },
  'orange dream': { aliases: ['Orange Dream'], shorthand: ['OD'] },
  'yellow belly': { aliases: ['Yellow Belly', 'Yellowbelly'], shorthand: ['YB'] },
  'black pastel': { aliases: ['Black Pastel'], shorthand: ['BP'] },
  'cinnamon': { aliases: ['Cinnamon'], shorthand: ['Cin', 'Cinn'] },
  'mojave': { aliases: ['Mojave'], shorthand: ['Moj'] },
  'lesser': { aliases: ['Lesser'], shorthand: ['Les'] },
  'butter': { aliases: ['Butter'], shorthand: ['But'] },
  'russo': { aliases: ['Russo'], shorthand: ['Rus'] },
  'mystic': { aliases: ['Mystic'], shorthand: ['Mys'] },
  'phantom': { aliases: ['Phantom'], shorthand: ['Phan'] },
  'special': { aliases: ['Special'], shorthand: ['Spec'] },
  'leopard': { aliases: ['Leopard'], shorthand: ['Leo'] },
  'spotnose': { aliases: ['Spotnose'], shorthand: ['SN'] },
  'pinstripe': { aliases: ['Pinstripe'], shorthand: ['Pin'] },
  'spider': { aliases: ['Spider'], shorthand: ['Spi'] },
  'enchi': { aliases: ['Enchi'], shorthand: ['En'] },
  'fire': { aliases: ['Fire'], shorthand: ['Fir'] },
  'vanilla': { aliases: ['Vanilla'], shorthand: ['Van'] },
  'red stripe': { aliases: ['Red Stripe'], shorthand: ['RS'] },
  'genetic stripe': { aliases: ['Genetic Stripe'], shorthand: ['GS'] },
  'desert ghost': { aliases: ['Desert Ghost'], shorthand: ['DG'] },
  'hypo (orange ghost)': { aliases: ['Hypo', 'Orange Ghost'], shorthand: ['OG'] },
  'clown': { aliases: ['Clown'], shorthand: ['Cln'] },
  'piebald': { aliases: ['Piebald'], shorthand: ['Pied', 'Pb'] },
  'lavender albino': { aliases: ['Lavender Albino'], shorthand: ['Lav', 'Lav Albino'] },
  'ultramel': { aliases: ['Ultramel', 'Ultramale', 'Ultra Male'], shorthand: ['UM'] },
  'monsoon': { aliases: ['Monsoon'], shorthand: ['Mons'] },
  'puzzle': { aliases: ['Puzzle'], shorthand: ['Puz'] },
  'sunset': { aliases: ['Sunset'], shorthand: ['Sun'] },
  'axanthic vpi': { aliases: ['Axanthic VPI', 'VPI Axanthic'], shorthand: ['VPI'] },
  'axanthic tsk': { aliases: ['Axanthic TSK', 'TSK Axanthic'], shorthand: ['TSK'] },
  'axanthic mj': { aliases: ['MJ Axanthic', 'Axanthic MJ'], shorthand: ['MJ'] },
  'blackhead': { aliases: ['Blackhead'], shorthand: ['BH'] },
  'ghi': { aliases: ['GHI'], shorthand: ['GHI'] },
  'mahogany': { aliases: ['Mahogany'], shorthand: ['Mah'] },
  'acid': { aliases: ['Acid'], shorthand: ['ACD'] },
  'hurricane': { aliases: ['Hurricane'], shorthand: ['Hur'] },
  'wookie': { aliases: ['Wookie'], shorthand: ['Woo'] },
  'stranger': { aliases: ['Stranger'], shorthand: ['Str'] },
  'confusion': { aliases: ['Confusion'], shorthand: ['Conf'] },
  'bongo': { aliases: ['Bongo'], shorthand: ['Bon'] },
  'cypress': { aliases: ['Cypress'], shorthand: ['Cyp'] },
  'specter': { aliases: ['Specter'], shorthand: ['Spc'] },
  'gravel': { aliases: ['Gravel'], shorthand: ['Gra'] },
  'asphalt': { aliases: ['Asphalt'], shorthand: ['Asp'] },
};

function normalizeAliasList(values: unknown): string[] {
  const arr = Array.isArray(values) ? values : [];
  const seen = new Set<string>();
  const out: string[] = [];
  arr.forEach((value) => {
    const cleaned = String(value || '').trim();
    const key = cleaned.toLowerCase();
    if (!cleaned || seen.has(key)) return;
    seen.add(key);
    out.push(cleaned);
  });
  return out;
}

function normalizeGeneRecord(raw: RawGeneRecord): GeneRecord | null {
  const geneName = String(raw?.geneName || '').trim();
  if (!geneName) return null;
  const geneKey = geneName.toLowerCase();
  const preset = DEFAULT_GENE_ALIAS_PRESETS[geneKey] || null;

  const aliases = normalizeAliasList([
    geneName,
    ...(Array.isArray(preset?.aliases) ? preset.aliases : []),
    ...(Array.isArray(raw?.aliases) ? raw.aliases : []),
  ]);
  const shorthand = normalizeAliasList([
    ...(Array.isArray(preset?.shorthand) ? preset.shorthand : []),
    ...(Array.isArray(raw?.shorthand) ? raw.shorthand : []),
  ]);

  const VALID_HEALTH_FLAGS = new Set(['wobble', 'lethal_super', 'infertility', 'kinking']);
  const healthFlags = (Array.isArray(raw.healthFlags) ? raw.healthFlags : [])
    .map(f => String(f).trim())
    .filter(f => VALID_HEALTH_FLAGS.has(f)) as HealthFlag[];

  return {
    geneName,
    geneType: raw.geneType,
    complex: raw.complex ?? null,
    hasSuperForm: Boolean(raw.hasSuperForm),
    superGeneName: raw.superGeneName ? String(raw.superGeneName).trim() : null,
    aliases,
    shorthand,
    healthFlags,
    equivalentNames: normalizeAliasList(Array.isArray(raw.equivalentNames) ? raw.equivalentNames : []),
    yearDiscovered: raw.yearDiscovered ?? null,
    rarity: raw.rarity ?? null,
    ...(raw.notes ? { notes: String(raw.notes) } : {}),
  };
}

/**
 * Everything the accessors below need for one species, built once per species and cached.
 * Previously these were module-level singletons over the one ball python table; they are
 * per-species now so switching species swaps the whole lookup set atomically instead of
 * leaving half the app resolving genes against the previous species.
 */
type GeneIndex = {
  speciesId: string;
  db: SpeciesGeneticsDatabase;
  byName: Map<string, GeneRecord>;
  byType: Map<GeneType, GeneRecord[]>;
  byComplex: Map<string, GeneRecord[]>;
  superNameToBase: Map<string, GeneRecord>;
  defaultAliasRows: GeneAliasRow[];
};

/**
 * Genes contributed by partner laboratories, keyed by species.
 *
 * The generated Morphpedia tables under config/species are never hand-edited -
 * regenerating them is routine, and an edit would be silently lost. A laboratory
 * that tests for something Morphpedia does not list needs that gene to exist
 * anyway, or a confirmed result has nothing to write back to the animal.
 *
 * So contributions live server-side and are layered over the generated table
 * here, at read time. A rebuild from Morphpedia cannot discard them, and the
 * provenance travels with each gene so a contributed one is never mistaken for a
 * curated one.
 *
 * What reaches this map has already been approved by a platform administrator,
 * except for a laboratory's own pending submissions when it is the one asking -
 * the backend decides that, not this file.
 */
const GENE_OVERLAYS = new Map<string, GeneRecord[]>();

/**
 * Installs the overlay for a species. Safe to call before or after the species
 * is active: if it is already loaded, its index is rebuilt so the new genes
 * appear immediately, and the generation bump tells memoizing callers to drop
 * their caches.
 */
export function setSpeciesGeneOverlay(rawSpeciesId: string, genes: unknown): void {
  const speciesId = resolveSpeciesId(rawSpeciesId);
  const records = (Array.isArray(genes) ? genes : [])
    .map(normalizeGeneRecord)
    .filter((entry): entry is GeneRecord => Boolean(entry));

  if (!records.length && !GENE_OVERLAYS.has(speciesId)) return;
  GENE_OVERLAYS.set(speciesId, records);

  // Rebuild from the generated table plus the new overlay, never from the
  // previous index - otherwise removing a gene from the overlay would leave it
  // behind forever.
  const base = BASE_TABLES.get(speciesId);
  if (base) {
    LOADED_INDEXES.set(speciesId, createGeneIndex(speciesId, base));
    if (speciesId === activeSpeciesId) {
      geneDatabaseGeneration += 1;
      rebuildActiveGeneAliasResolver();
    }
  }
}

export function getSpeciesGeneOverlay(speciesId: string): GeneRecord[] {
  return GENE_OVERLAYS.get(resolveSpeciesId(speciesId)) || [];
}

/**
 * The generated tables as loaded, before any overlay. Kept so an index can
 * always be rebuilt from a known-clean base.
 */
const BASE_TABLES = new Map<string, unknown>();

function createGeneIndex(speciesId: string, raw: unknown): GeneIndex {
  const rawDb = (raw || {}) as RawDatabase;
  const generated = (Array.isArray(rawDb.genes) ? rawDb.genes : [])
    .map(normalizeGeneRecord)
    .filter((entry): entry is GeneRecord => Boolean(entry));

  // Laboratory contributions layer over the generated table. A contribution
  // never replaces a curated gene of the same name: Morphpedia is the authority
  // on genes it documents, and a lab proposing one it already lists is a
  // duplicate rather than a correction.
  const generatedNames = new Set(generated.map((gene) => gene.geneName.trim().toLowerCase()));
  const contributed = (GENE_OVERLAYS.get(speciesId) || []).filter(
    (gene) => !generatedNames.has(gene.geneName.trim().toLowerCase())
  );

  const db: SpeciesGeneticsDatabase = {
    ...rawDb,
    groups: rawDb.groups || ({} as GeneGroups),
    genes: [...generated, ...contributed],
  };

  const index: GeneIndex = {
    speciesId,
    db,
    byName: new Map(),
    byType: new Map(),
    byComplex: new Map(),
    superNameToBase: new Map(),
    defaultAliasRows: [],
  };

  db.genes.forEach((gene) => {
    const key = String(gene.geneName || '').trim().toLowerCase();
    if (!key) return;
    if (!index.byName.has(key)) index.byName.set(key, gene);

    const bucket = index.byType.get(gene.geneType) || [];
    bucket.push(gene);
    index.byType.set(gene.geneType, bucket);

    if (gene.complex) {
      const complexKey = gene.complex.toLowerCase();
      const complexBucket = index.byComplex.get(complexKey) || [];
      complexBucket.push(gene);
      index.byComplex.set(complexKey, complexBucket);
    }

    if (gene.superGeneName) {
      index.superNameToBase.set(gene.superGeneName.trim().toLowerCase(), gene);
    }

    index.defaultAliasRows.push({
      geneName: gene.geneName,
      aliases: normalizeAliasList(gene.aliases),
      shorthand: normalizeAliasList(gene.shorthand),
    });
  });

  return index;
}

/**
 * Species with a gene table loaded. Ball python is present from module load; the rest are
 * added by setActiveSpecies as they are needed.
 */
const LOADED_INDEXES = new Map<string, GeneIndex>([
  [DEFAULT_SPECIES_ID, createGeneIndex(DEFAULT_SPECIES_ID, ballPythonJson)],
]);

// Ball python is statically imported rather than loaded through
// setActiveSpecies, so its base table is registered here; without it an overlay
// for the default species would have nothing clean to rebuild from.
BASE_TABLES.set(DEFAULT_SPECIES_ID, ballPythonJson);

/**
 * Species that legitimately have no gene table (most of the 64 -- Morphpedia publishes no
 * traits for them). They get an empty index so the app stays usable: a keeper can still
 * record animals and pair them, there is just nothing to predict.
 */
const EMPTY_INDEX_CACHE = new Map<string, GeneIndex>();
function emptyIndexFor(speciesId: string): GeneIndex {
  const cached = EMPTY_INDEX_CACHE.get(speciesId);
  if (cached) return cached;
  const index = createGeneIndex(speciesId, {
    version: 1,
    generatedAt: '',
    genes: [],
    groups: {},
  });
  EMPTY_INDEX_CACHE.set(speciesId, index);
  return index;
}

let activeSpeciesId: string = DEFAULT_SPECIES_ID;

/**
 * Bumped whenever the active species changes. Callers that memoize anything derived from
 * the gene database (see geneLibrary) key their cache on this so a species switch cannot
 * leave them serving the previous species' genes.
 */
let geneDatabaseGeneration = 0;

/** Sequence number for setActiveSpecies, so a slow load cannot overwrite a newer switch. */
let latestSpeciesRequest = 0;


export function getGeneDatabaseGeneration(): number {
  return geneDatabaseGeneration;
}

function activeIndex(): GeneIndex {
  return LOADED_INDEXES.get(activeSpeciesId) || emptyIndexFor(activeSpeciesId);
}

export function getActiveSpeciesId(): string {
  return activeSpeciesId;
}

/** True once this species' gene table is in memory and can be switched to synchronously. */
export function isSpeciesGeneTableLoaded(speciesId: string): boolean {
  return LOADED_INDEXES.has(resolveSpeciesId(speciesId));
}

/**
 * Points the whole genetics layer at another species. Async because trait tables are code
 * split -- a keeper working one species should not pay to download the other 21.
 *
 * Resolves to the species id actually in effect, which is the requested one unless it is
 * unknown, in which case it falls back to ball python rather than leaving the app with no
 * gene database at all.
 */
export async function setActiveSpecies(rawSpeciesId: string | null | undefined): Promise<string> {
  const speciesId = resolveSpeciesId(rawSpeciesId);
  if (speciesId === activeSpeciesId) return activeSpeciesId;

  // A keeper scrolling a species dropdown fires several of these, and a big table can
  // resolve after a smaller one requested later. Only the newest request may take effect,
  // or the app ends up on a species nobody asked for.
  const request = ++latestSpeciesRequest;

  if (!LOADED_INDEXES.has(speciesId)) {
    const species = getSpeciesById(speciesId);
    if (species?.traitsFile) {
      const raw = await loadSpeciesGeneTable(speciesId);
      // Caching the table is safe whoever won -- it is the load that was slow, not the
      // switch, and the next request for this species should not pay for it again.
      if (raw && !LOADED_INDEXES.has(speciesId)) {
        BASE_TABLES.set(speciesId, raw);
        LOADED_INDEXES.set(speciesId, createGeneIndex(speciesId, raw));
      }
    }
  }

  if (request !== latestSpeciesRequest) return activeSpeciesId;

  activeSpeciesId = speciesId;
  geneDatabaseGeneration += 1;
  // The alias resolver is built from the active species' gene names, so it has to be
  // rebuilt too -- otherwise a crested gecko cross would keep resolving ball python
  // shorthand like "YB" and silently invent genes the species does not have.
  rebuildActiveGeneAliasResolver();
  return activeSpeciesId;
}

export function getActiveGeneticsDatabase(): SpeciesGeneticsDatabase {
  return activeIndex().db;
}

export function normalizeGeneAliasRows(rows: unknown): GeneAliasRow[] {
  const source = Array.isArray(rows) ? rows : [];
  const out: GeneAliasRow[] = [];
  const byGene = new Map<string, GeneAliasRow>();

  source.forEach((entry: any) => {
    const geneName = String(entry?.geneName || '').trim();
    if (!geneName) return;
    const key = geneName.toLowerCase();
    const existing = byGene.get(key) || { geneName, aliases: [], shorthand: [] };
    existing.geneName = geneName;
    existing.aliases = normalizeAliasList([...existing.aliases, ...(Array.isArray(entry?.aliases) ? entry.aliases : []), geneName]);
    existing.shorthand = normalizeAliasList([...existing.shorthand, ...(Array.isArray(entry?.shorthand) ? entry.shorthand : [])]);
    byGene.set(key, existing);
  });

  byGene.forEach(value => out.push(value));
  return out.sort((a, b) => a.geneName.localeCompare(b.geneName, undefined, { sensitivity: 'base' }));
}

export function getDefaultGeneAliasRows(): GeneAliasRow[] {
  return activeIndex().defaultAliasRows.map(row => ({
    geneName: row.geneName,
    aliases: row.aliases.slice(),
    shorthand: row.shorthand.slice(),
  }));
}

export function mergeGeneAliasRows(customRows: unknown): GeneAliasRow[] {
  const defaults = getDefaultGeneAliasRows();
  const merged = new Map<string, GeneAliasRow>();

  defaults.forEach((row) => {
    merged.set(row.geneName.toLowerCase(), {
      geneName: row.geneName,
      aliases: normalizeAliasList(row.aliases),
      shorthand: normalizeAliasList(row.shorthand),
    });
  });

  normalizeGeneAliasRows(customRows).forEach((row) => {
    const key = row.geneName.toLowerCase();
    const prior = merged.get(key);
    if (!prior) {
      merged.set(key, {
        geneName: row.geneName,
        aliases: normalizeAliasList([row.geneName, ...row.aliases]),
        shorthand: normalizeAliasList(row.shorthand),
      });
      return;
    }
    merged.set(key, {
      geneName: prior.geneName,
      aliases: normalizeAliasList([...prior.aliases, ...row.aliases, row.geneName]),
      shorthand: normalizeAliasList([...prior.shorthand, ...row.shorthand]),
    });
  });

  return Array.from(merged.values()).sort((a, b) => a.geneName.localeCompare(b.geneName, undefined, { sensitivity: 'base' }));
}

export function buildGeneAliasLookupMap(rows: unknown): Map<string, string> {
  const map = new Map<string, string>();
  const normalized = normalizeGeneAliasRows(rows);

  normalized.forEach((row) => {
    const canonical = row.geneName;
    const variants = normalizeAliasList([canonical, ...row.aliases, ...row.shorthand]);
    variants.forEach((variant) => {
      const key = variant.toLowerCase();
      if (!key || map.has(key)) return;
      map.set(key, canonical);
    });
  });

  return map;
}

export function resolveGeneAliasToken(token: string, lookupMap: Map<string, string>): string | null {
  const direct = String(token || '').trim();
  if (!direct) return null;
  const key = direct.toLowerCase();
  if (lookupMap.has(key)) return lookupMap.get(key) || null;

  const compact = direct
    .replace(/[()]/g, ' ')
    .replace(/[-_/]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
  if (!compact) return null;
  return lookupMap.get(compact) || null;
}

let ACTIVE_GENE_ALIAS_ROWS: GeneAliasRow[] = [];
let ACTIVE_GENE_ALIAS_LOOKUP = new Map<string, string>();
/**
 * The keeper's own alias rows, kept apart from the merged result so they can be re-merged
 * against a different species' defaults. Without this, switching species would silently
 * discard every alias the keeper had defined.
 */
let CUSTOM_GENE_ALIAS_ROWS: unknown = null;

/**
 * Drops supplied alias rows that name a gene belonging to a DIFFERENT loaded species.
 *
 * The app persists a single alias table, already merged against whatever species was
 * active when it was saved. Re-applying it wholesale after a switch would leave ball python
 * shorthand like "YB" resolving under crested geckos -- inventing a gene the animal cannot
 * carry, which a cross would then happily predict.
 *
 * Rows naming a gene no loaded species claims are kept: those are the keeper's own, and
 * discarding them would lose real data. Only loaded species can be checked, so a leaked row
 * from a species never opened this session survives; that is the same table the keeper saw
 * a moment ago, so it is the safe way to be wrong.
 */
function rowsBelongingToActiveSpecies(rows: unknown): GeneAliasRow[] {
  const active = activeIndex();
  return normalizeGeneAliasRows(rows).filter((row) => {
    const key = row.geneName.trim().toLowerCase();
    if (active.byName.has(key)) return true;
    for (const index of LOADED_INDEXES.values()) {
      if (index !== active && index.byName.has(key)) return false;
    }
    return true;
  });
}

function rebuildActiveGeneAliasResolver() {
  const custom = CUSTOM_GENE_ALIAS_ROWS === null
    ? getDefaultGeneAliasRows()
    : rowsBelongingToActiveSpecies(CUSTOM_GENE_ALIAS_ROWS);
  const merged = mergeGeneAliasRows(custom);
  ACTIVE_GENE_ALIAS_ROWS = merged;
  ACTIVE_GENE_ALIAS_LOOKUP = buildGeneAliasLookupMap(merged);
}

function ensureActiveGeneAliasResolver() {
  if (!ACTIVE_GENE_ALIAS_ROWS.length || !ACTIVE_GENE_ALIAS_LOOKUP.size) {
    rebuildActiveGeneAliasResolver();
  }
}

export function getActiveGeneAliasRows(): GeneAliasRow[] {
  ensureActiveGeneAliasResolver();
  return ACTIVE_GENE_ALIAS_ROWS.map(row => ({
    geneName: row.geneName,
    aliases: row.aliases.slice(),
    shorthand: row.shorthand.slice(),
  }));
}

export function setActiveGeneAliasRows(rows: unknown): GeneAliasRow[] {
  CUSTOM_GENE_ALIAS_ROWS = rows;
  rebuildActiveGeneAliasResolver();
  return getActiveGeneAliasRows();
}

export function resolveActiveGeneAliasToken(token: string): string | null {
  ensureActiveGeneAliasResolver();
  return resolveGeneAliasToken(token, ACTIVE_GENE_ALIAS_LOOKUP);
}

export function resolveCanonicalGene(
  token: string,
  resolveCanonical?: (raw: string) => string | null
): string | null {
  const raw = String(token || '').trim();
  if (!raw) return null;
  if (typeof resolveCanonical === 'function') {
    const canonical = resolveCanonical(raw);
    if (canonical) return canonical;
  }
  return resolveActiveGeneAliasToken(raw);
}

const POSSIBLE_HET_WORDS = new Set(['possible', 'probable', 'maybe', 'ph']);

function normalizeGeneSearchPhrase(value: unknown): string {
  return String(value ?? '')
    .toLowerCase()
    .replace(/[()]/g, ' ')
    .replace(/[^a-z0-9%]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function titleCaseWords(value: string): string {
  return String(value || '')
    .split(' ')
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ');
}

export function extractTraitsFromMorphText(raw: string, rows?: unknown): string[] {
  const normalized = normalizeGeneSearchPhrase(raw);
  if (!normalized) return [];

  const aliasRows = Array.isArray(rows) && rows.length ? normalizeGeneAliasRows(rows) : getActiveGeneAliasRows();
  const phraseMap = new Map<string, string>();
  let maxAliasWords = 1;

  aliasRows.forEach((row) => {
    const canonical = String(row?.geneName || '').trim();
    if (!canonical) return;
    const variants = [canonical, ...(Array.isArray(row?.aliases) ? row.aliases : []), ...(Array.isArray(row?.shorthand) ? row.shorthand : [])];
    variants.forEach((variant) => {
      const key = normalizeGeneSearchPhrase(variant);
      if (!key || phraseMap.has(key)) return;
      phraseMap.set(key, canonical);
      const wordCount = key.split(' ').filter(Boolean).length;
      if (wordCount > maxAliasWords) {
        maxAliasWords = wordCount;
      }
    });
  });

  const words = normalized.split(' ').filter(Boolean);
  const traits: string[] = [];
  const seen = new Set<string>();

  let idx = 0;
  while (idx < words.length) {
    let matchedCanonical = '';
    let matchedLength = 0;

    for (let size = Math.min(maxAliasWords, words.length - idx); size >= 1; size -= 1) {
      const phrase = words.slice(idx, idx + size).join(' ');
      const canonical = phraseMap.get(phrase);
      if (canonical) {
        matchedCanonical = canonical;
        matchedLength = size;
        break;
      }
    }

    if (!matchedCanonical || !matchedLength) {
      idx += 1;
      continue;
    }

    const lookback = words.slice(Math.max(0, idx - 4), idx);
    const hasHet = lookback.includes('het');
    const hasSuper = lookback.includes('super');
    const qualifier = lookback.find((word) => POSSIBLE_HET_WORDS.has(word)) || '';
    const percent = lookback.find((word) => /^\d{1,3}%$/.test(word)) || '';
    const qualifierLabel = qualifier ? titleCaseWords(qualifier) : '';

    const parts: string[] = [];
    if (hasSuper) parts.push('Super');
    if (hasHet && percent) parts.push(percent);
    if (hasHet && qualifierLabel) parts.push(qualifierLabel);
    if (hasHet) parts.push('Het');
    parts.push(matchedCanonical);

    const trait = parts.join(' ').replace(/\s+/g, ' ').trim();
    const key = trait.toLowerCase();
    if (trait && !seen.has(key)) {
      seen.add(key);
      traits.push(trait);
    }

    idx += matchedLength;
  }

  return traits;
}

export function getAllGenes(): GeneRecord[] {
  return activeIndex().db.genes.slice();
}

export function getGeneByName(geneName: string): GeneRecord | null {
  const key = String(geneName || '').trim().toLowerCase();
  if (!key) return null;
  return activeIndex().byName.get(key) || null;
}

export function getGenesByType(geneType: GeneType): GeneRecord[] {
  return (activeIndex().byType.get(geneType) || []).slice();
}

export function getGenesByComplex(complexName: string): GeneRecord[] {
  const key = String(complexName || '').trim().toLowerCase();
  if (!key) return [];
  return (activeIndex().byComplex.get(key) || []).slice();
}

export function getGroup(groupName: keyof GeneGroups): string[] {
  const group = activeIndex().db.groups[groupName];
  return Array.isArray(group) ? group.slice() : [];
}

export function getSuperFormForGene(geneName: string): string | null {
  const gene = getGeneByName(geneName);
  if (!gene || !gene.hasSuperForm || !gene.superGeneName) return null;
  return gene.superGeneName;
}

export function getBaseGeneForSuper(superGeneName: string): GeneRecord | null {
  const key = String(superGeneName || '').trim().toLowerCase();
  if (!key) return null;
  return activeIndex().superNameToBase.get(key) || null;
}

export function buildAliasRecognitionSeed(): string[] {
  const names = new Set<string>();
  activeIndex().db.genes.forEach((gene) => {
    if (gene.geneName) names.add(gene.geneName);
    if (gene.superGeneName) names.add(gene.superGeneName);
    (gene.aliases || []).forEach(alias => names.add(alias));
    (gene.shorthand || []).forEach(short => names.add(short));
  });
  return [...names];
}

/**
 * Every interchangeable label for a gene, canonical name first.
 * "Hurricane" -> ["Trick", "Hurricane", "Blitz"].
 *
 * Returns a single-entry list for genes with no equivalents, so callers never special-case.
 */
export function getEquivalentGeneNames(rawGene: string | null | undefined): string[] {
  const gene = getGeneByName(String(rawGene ?? '')) ;
  if (!gene) {
    const trimmed = String(rawGene ?? '').trim();
    return trimmed ? [trimmed] : [];
  }
  return normalizeAliasList([gene.geneName, ...(gene.equivalentNames || [])]);
}

/**
 * Display label that keeps the keeper's chosen name and shows the other trade names for the
 * same allele: "Hurricane" -> "Hurricane (Trick, Blitz)".
 *
 * The chosen name is preserved verbatim rather than collapsed onto the canonical name --
 * two keepers can call one allele different things and both stay correct.
 */
export function formatGeneWithEquivalents(rawGene: string | null | undefined): string {
  const chosen = String(rawGene ?? '').trim();
  if (!chosen) return '';
  const all = getEquivalentGeneNames(chosen);
  if (all.length < 2) return chosen;

  const chosenKey = chosen.toLowerCase();
  const match = all.find(name => name.toLowerCase() === chosenKey);
  const label = match || chosen;
  const others = all.filter(name => name.toLowerCase() !== label.toLowerCase());
  return others.length ? `${label} (${others.join(', ')})` : label;
}

/**
 * Canonical key that GENETICS must use. Trick, Hurricane and Blitz are one allele, so a
 * cross has to collapse them to a single locus even though each is displayed as chosen --
 * treating them as separate genes would predict impossible offspring.
 */
export function resolveGeneIdentity(rawGene: string | null | undefined): string | null {
  const gene = getGeneByName(String(rawGene ?? ''));
  if (gene) return gene.geneName;
  return resolveCanonicalGene(String(rawGene ?? '')) || null;
}
