// The catalogue of species the app knows about, and the loader for their gene tables.
//
// Both the taxonomy and the per-species trait tables are generated by
// scripts/species/buildSpeciesDatabase.mjs into src/config/species/. Nothing here is
// hand-maintained: adding a species means adding it to the generator's source tables and
// rebuilding, never editing this file.
import indexJson from '../config/species/index.json';

/**
 * Ball pythons are the app's original and only species, so every animal recorded before
 * multi-species support is implicitly one. Its table is statically imported (see
 * geneDatabase.ts) so the app still boots with a usable gene database synchronously.
 */
export const DEFAULT_SPECIES_ID = 'ball-python';

export type ReproductionMode = 'egg_laying' | 'live_bearing';

export type SpeciesSummary = {
  id: string;
  name: string;
  group: string;
  groupName: string;
  scientificName: string | null;
  reproduction: ReproductionMode;
  /** Sub-kinds Morphpedia lists under one heading (e.g. Argentine / Columbian Tegus). */
  variants: string[];
  traitCount: number;
  /**
   * File name of this species' gene table, or null when Morphpedia publishes no traits for
   * it. A null here is not a gap to fill later -- most of the 64 species genuinely have no
   * documented morphs, and the app must stay usable for them without a gene database.
   */
  traitsFile: string | null;
};

export type SpeciesGroup = {
  id: string;
  name: string;
  sourceNote: string | null;
  speciesIds: string[];
};

type SpeciesIndexDocument = {
  version: number;
  generatedAt: string;
  source: string;
  groups: SpeciesGroup[];
  species: SpeciesSummary[];
};

const INDEX = indexJson as SpeciesIndexDocument;

const bySpeciesId = new Map<string, SpeciesSummary>();
INDEX.species.forEach((species) => {
  bySpeciesId.set(species.id, species);
});

/**
 * Lazy loaders keyed by species id. Deliberately NOT eager: the trait tables total a
 * quarter of a megabyte, and a keeper who only works one species should never download the
 * other 21. Ball python is the exception -- geneDatabase.ts imports it statically because
 * the app must have a gene database before any species has been chosen.
 */
const TRAIT_FILE_LOADERS: Record<string, () => Promise<unknown>> = (() => {
  const modules = import.meta.glob('../config/species/*.json');
  const loaders: Record<string, () => Promise<unknown>> = {};
  Object.entries(modules).forEach(([path, loader]) => {
    const fileName = path.split('/').pop() || '';
    const id = fileName.replace(/\.json$/, '');
    if (!id || id === 'index') return;
    loaders[id] = loader;
  });
  return loaders;
})();

export function listSpecies(): SpeciesSummary[] {
  return INDEX.species.slice();
}

export function listSpeciesGroups(): SpeciesGroup[] {
  return INDEX.groups.map((group) => ({ ...group, speciesIds: group.speciesIds.slice() }));
}

export function getSpeciesById(speciesId: string | null | undefined): SpeciesSummary | null {
  const key = String(speciesId ?? '').trim();
  if (!key) return null;
  return bySpeciesId.get(key) || null;
}

/** True when this species has a gene table to load -- see SpeciesSummary.traitsFile. */
export function speciesHasGeneDatabase(speciesId: string | null | undefined): boolean {
  const species = getSpeciesById(speciesId);
  return Boolean(species?.traitsFile);
}

/**
 * Coerces stored or user-supplied species values to a known id, falling back to ball
 * python. Animals synced from before the species column existed carry null, and the
 * backend leaves that null on purpose rather than baking in a guess -- resolving it here
 * keeps the assumption in one correctable place.
 */
export function resolveSpeciesId(rawSpeciesId: unknown): string {
  const key = String(rawSpeciesId ?? '').trim();
  if (key && bySpeciesId.has(key)) return key;
  return DEFAULT_SPECIES_ID;
}

/**
 * Loads a species' raw gene table. Resolves to null for species Morphpedia publishes no
 * traits for -- that is a normal outcome, not an error.
 */
export async function loadSpeciesGeneTable(speciesId: string): Promise<unknown | null> {
  const species = getSpeciesById(speciesId);
  if (!species || !species.traitsFile) return null;
  const loader = TRAIT_FILE_LOADERS[speciesId];
  if (!loader) return null;
  const mod = (await loader()) as { default?: unknown };
  return mod?.default ?? mod;
}
