// ============================================================
// MOCK DATA — Isolated from production logic.
// TODO: Replace with real API calls when backend is ready.
// See api/familyTreeApi.js for the intended endpoint shapes.
// ============================================================

export const MOCK_BREEDERS = [
  { id: 'breeder-001', name: 'Apex Reptiles', location: 'Austin, TX' },
  { id: 'breeder-002', name: 'Star Scales', location: 'Denver, CO' },
];

export const MOCK_SNAKES = [
  // ── Generation -2: Paternal grandparents ──────────────────
  {
    id: 'snake-titan',
    globalId: 'BP-2016-0001',
    localId: 'TT-001',
    name: 'Titan',
    species: 'Ball Python',
    sex: 'male',
    genetics: ['Pastel', 'Spider'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-001',
    clutchId: null,
    hatchDate: '2016-05-10',
    status: 'retired',
    privacyLevel: 'public',
    photoUrl: null,
  },
  {
    id: 'snake-luna',
    globalId: 'BP-2016-0002',
    localId: 'LN-001',
    name: 'Luna',
    species: 'Ball Python',
    sex: 'female',
    genetics: ['Cinnamon'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-001',
    clutchId: null,
    hatchDate: '2016-08-22',
    status: 'retired',
    privacyLevel: 'public',
    photoUrl: null,
  },
  // ── Generation -2: Maternal grandparents ─────────────────
  {
    id: 'snake-blaze',
    globalId: 'BP-2017-0001',
    localId: 'BZ-001',
    name: 'Blaze',
    species: 'Ball Python',
    sex: 'male',
    genetics: ['Yellow Belly'],
    breederId: 'breeder-002',
    breederName: 'Star Scales',
    currentOwnerId: 'breeder-002',
    clutchId: null,
    hatchDate: '2017-06-15',
    status: 'breeding',
    privacyLevel: 'public',
    photoUrl: null,
  },
  {
    id: 'snake-iris',
    globalId: 'BP-2017-0002',
    localId: 'IR-001',
    name: 'Iris',
    species: 'Ball Python',
    sex: 'female',
    genetics: ['Lesser'],
    breederId: 'breeder-002',
    breederName: 'Star Scales',
    currentOwnerId: 'breeder-002',
    clutchId: null,
    hatchDate: '2017-09-03',
    status: 'breeding',
    privacyLevel: 'public',
    photoUrl: null,
  },
  // ── Generation -1: Parents ────────────────────────────────
  {
    id: 'snake-apollo',
    globalId: 'BP-2019-0001',
    localId: 'AP-001',
    name: 'Apollo',
    species: 'Ball Python',
    sex: 'male',
    genetics: ['Pastel', 'Cinnamon', 'Spider'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-001',
    clutchId: 'clutch-c19-001',
    hatchDate: '2019-07-12',
    status: 'breeding',
    privacyLevel: 'public',
    photoUrl: null,
  },
  {
    id: 'snake-stella',
    globalId: 'BP-2020-0001',
    localId: 'ST-001',
    name: 'Stella',
    species: 'Ball Python',
    sex: 'female',
    genetics: ['Yellow Belly', 'Lesser'],
    breederId: 'breeder-002',
    breederName: 'Star Scales',
    currentOwnerId: 'breeder-001',
    clutchId: 'clutch-c20-001',
    hatchDate: '2020-08-05',
    status: 'breeding',
    privacyLevel: 'public',
    photoUrl: null,
  },
  // ── Generation 0: Selected snake ──────────────────────────
  {
    id: 'snake-nova',
    globalId: 'BP-2022-0001',
    localId: 'NV-001',
    name: 'Nova',
    species: 'Ball Python',
    sex: 'female',
    genetics: ['Pastel', 'Cinnamon', 'Yellow Belly', 'Lesser'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-001',
    clutchId: 'clutch-c22-001',
    hatchDate: '2022-06-18',
    status: 'breeding',
    privacyLevel: 'public',
    photoUrl: null,
  },
  // ── Generation +1: Offspring ──────────────────────────────
  {
    id: 'snake-comet',
    globalId: 'BP-2024-0001',
    localId: 'CM-001',
    name: 'Comet',
    species: 'Ball Python',
    sex: 'male',
    genetics: ['Pastel', 'Yellow Belly'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-001',
    clutchId: 'clutch-c24-001',
    hatchDate: '2024-07-01',
    status: 'holdback',
    privacyLevel: 'public',
    photoUrl: null,
  },
  {
    id: 'snake-lyra',
    globalId: 'BP-2024-0002',
    localId: 'LR-001',
    name: 'Lyra',
    species: 'Ball Python',
    sex: 'female',
    genetics: ['Cinnamon', 'Lesser'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-003',
    clutchId: 'clutch-c24-001',
    hatchDate: '2024-07-01',
    status: 'sold',
    privacyLevel: 'shared',
    photoUrl: null,
  },
  {
    id: 'snake-vega',
    globalId: 'BP-2024-0003',
    localId: 'VG-001',
    name: 'Vega',
    species: 'Ball Python',
    sex: 'male',
    genetics: ['Pastel', 'Cinnamon'],
    breederId: 'breeder-001',
    breederName: 'Apex Reptiles',
    currentOwnerId: 'breeder-001',
    clutchId: 'clutch-c24-001',
    hatchDate: '2024-07-01',
    status: 'holdback',
    privacyLevel: 'public',
    photoUrl: null,
  },
];

// role: 'sire' | 'dam'
// confidence: 'confirmed' | 'reported' | 'unknown'
export const MOCK_PARENT_RELATIONSHIPS = [
  { id: 'pr-001', childId: 'snake-apollo', parentId: 'snake-titan', role: 'sire', confidence: 'confirmed' },
  { id: 'pr-002', childId: 'snake-apollo', parentId: 'snake-luna', role: 'dam', confidence: 'confirmed' },
  { id: 'pr-003', childId: 'snake-stella', parentId: 'snake-blaze', role: 'sire', confidence: 'confirmed' },
  { id: 'pr-004', childId: 'snake-stella', parentId: 'snake-iris', role: 'dam', confidence: 'confirmed' },
  { id: 'pr-005', childId: 'snake-nova', parentId: 'snake-apollo', role: 'sire', confidence: 'confirmed' },
  { id: 'pr-006', childId: 'snake-nova', parentId: 'snake-stella', role: 'dam', confidence: 'confirmed' },
  { id: 'pr-007', childId: 'snake-comet', parentId: 'snake-nova', role: 'dam', confidence: 'confirmed' },
  { id: 'pr-008', childId: 'snake-lyra', parentId: 'snake-nova', role: 'dam', confidence: 'confirmed' },
  { id: 'pr-009', childId: 'snake-vega', parentId: 'snake-nova', role: 'dam', confidence: 'confirmed' },
];

export const MOCK_CLUTCHES = [
  {
    id: 'clutch-c19-001',
    displayId: 'CL-2019-001',
    sireId: 'snake-titan',
    damId: 'snake-luna',
    breederId: 'breeder-001',
    hatchDate: '2019-07-12',
    eggCount: 8,
    hatchCount: 7,
    notes: 'First pairing. Excellent hatch rate.',
  },
  {
    id: 'clutch-c20-001',
    displayId: 'CL-2020-001',
    sireId: 'snake-blaze',
    damId: 'snake-iris',
    breederId: 'breeder-002',
    hatchDate: '2020-08-05',
    eggCount: 6,
    hatchCount: 5,
    notes: 'Cross-breeder clutch.',
  },
  {
    id: 'clutch-c22-001',
    displayId: 'CL-2022-001',
    sireId: 'snake-apollo',
    damId: 'snake-stella',
    breederId: 'breeder-001',
    hatchDate: '2022-06-18',
    eggCount: 7,
    hatchCount: 6,
    notes: 'Goal: Pastel Cinnamon YB Lesser. 4-gene animal produced.',
  },
  {
    id: 'clutch-c24-001',
    displayId: 'CL-2024-001',
    sireId: null,
    damId: 'snake-nova',
    breederId: 'breeder-001',
    hatchDate: '2024-07-01',
    eggCount: 5,
    hatchCount: 3,
    notes: 'Current season clutch. Sire not recorded.',
  },
];

// transferType: 'bred' | 'sale' | 'gift' | 'trade' | 'breeding_loan'
export const MOCK_OWNERSHIP_HISTORY = [
  { id: 'oh-001', snakeId: 'snake-nova', ownerId: 'breeder-001', ownerName: 'Apex Reptiles', fromDate: '2022-06-18', toDate: null, transferType: 'bred' },
  { id: 'oh-002', snakeId: 'snake-stella', ownerId: 'breeder-002', ownerName: 'Star Scales', fromDate: '2020-08-05', toDate: '2021-03-15', transferType: 'bred' },
  { id: 'oh-003', snakeId: 'snake-stella', ownerId: 'breeder-001', ownerName: 'Apex Reptiles', fromDate: '2021-03-15', toDate: null, transferType: 'sale' },
  { id: 'oh-004', snakeId: 'snake-lyra', ownerId: 'breeder-001', ownerName: 'Apex Reptiles', fromDate: '2024-07-01', toDate: '2024-09-20', transferType: 'bred' },
  { id: 'oh-005', snakeId: 'snake-lyra', ownerId: 'breeder-003', ownerName: 'Nexus Reptiles', fromDate: '2024-09-20', toDate: null, transferType: 'sale' },
];

export const MOCK_STATS = {
  totalSnakes: 10,
  totalClutches: 4,
  totalBreeders: 2,
  totalBloodlines: 3,
  generationsTracked: 3,
  networkStatus: 'online',
};

export const DEFAULT_SELECTED_SNAKE_ID = 'snake-nova';
