export type FeatureCatalogSeed = {
  featureKey: string;
  featureName: string;
  featureGroup: string;
  description?: string;
  defaultLimitType?: string | null;
};

const feature = (
  featureGroup: string,
  featureKey: string,
  featureName: string,
  defaultLimitType: string | null = null
): FeatureCatalogSeed => ({
  featureGroup,
  featureKey,
  featureName,
  description: `${featureName} access`,
  defaultLimitType,
});

export const FEATURE_CATALOG: FeatureCatalogSeed[] = [
  feature("Animal Management", "animals.view", "View animals"),
  feature("Animal Management", "animals.create", "Add animals", "count"),
  feature("Animal Management", "animals.edit", "Edit animals"),
  feature("Animal Management", "animals.delete", "Delete animals"),
  feature("Animal Management", "animals.photos", "Animal photos", "count"),
  feature("Animal Management", "animals.documents", "Animal documents", "count"),
  feature("Animal Management", "animals.notes", "Animal notes"),
  feature("Animal Management", "animals.health_logs", "Animal health logs"),
  feature("Animal Management", "animals.feeding_logs", "Animal feeding logs"),
  feature("Animal Management", "animals.weight_logs", "Animal weight logs"),
  feature("Animal Management", "animals.shedding_logs", "Animal shedding logs"),
  feature("Breeding", "breeding.pairings", "Pairings"),
  feature("Breeding", "breeding.lock_tracking", "Lock tracking"),
  feature("Breeding", "breeding.ovulation_tracking", "Ovulation tracking"),
  feature("Breeding", "breeding.egg_tracking", "Egg tracking"),
  feature("Breeding", "breeding.clutches", "Clutch management"),
  feature("Breeding", "breeding.hatchlings", "Hatchling management"),
  feature("Breeding", "breeding.calendar", "Breeding calendar"),
  feature("Breeding", "breeding.multi_generation_planner", "Multi-generation breeding planner"),
  feature("Breeding", "breeding.advisor", "Breeding goal advisor"),
  feature("Breeding", "breeding.pairing_recommendations", "Pairing recommendations"),
  feature("Genetics", "genetics.basic_calculator", "Basic genetics calculator"),
  feature("Genetics", "genetics.advanced_calculator", "Advanced genetics calculator"),
  feature("Genetics", "genetics.het_probability", "Het probability calculator"),
  feature("Genetics", "genetics.bel_helper", "BEL complex helper"),
  feature("Genetics", "genetics.multi_generation_planner", "Multi-generation genetics planner"),
  feature("Genetics", "genetics.aliases", "Genetic aliases database"),
  feature("Genetics", "genetics.morph_id", "Morph ID assistant"),
  feature("Genetics", "genetics.visual_comparison", "Visual morph comparison"),
  feature("Spaces", "spaces.rooms", "Rooms", "count"),
  feature("Spaces", "spaces.racks", "Racks", "count"),
  feature("Spaces", "spaces.terrariums", "Terrariums"),
  feature("Spaces", "spaces.tub_visualizer", "Tub visualizer"),
  feature("Spaces", "spaces.rack_occupancy", "Rack occupancy"),
  feature("Spaces", "spaces.cleaning_schedules", "Cleaning schedules"),
  feature("Spaces", "spaces.water_schedules", "Water schedules"),
  feature("Spaces", "spaces.capacity_planner", "Space capacity planning"),
  feature("QR / Labels", "qr.generate", "Generate animal QR codes", "monthly"),
  feature("QR / Labels", "qr.pdf_export", "Export QR labels to PDF", "monthly"),
  feature("QR / Labels", "qr.custom_labels", "Custom label sizes"),
  feature("QR / Labels", "qr.batch_export", "Batch QR export", "monthly"),
  feature("QR / Labels", "qr.shed_label_packs", "Shed test label packs"),
  feature("QR / Labels", "qr.shipping_labels", "Shipping labels"),
  feature("QR / Labels", "qr.rack_labels", "Rack labels"),
  feature("QR / Labels", "qr.tub_labels", "Tub labels"),
  feature("Communication Center", "communication.telegram", "Telegram connection", "monthly"),
  feature("Communication Center", "communication.telegram_updates", "Telegram message updates", "monthly"),
  feature("Communication Center", "communication.telegram_confirmation", "Telegram confirmation flow"),
  feature("Communication Center", "communication.inbox", "In-app inbox"),
  feature("Communication Center", "communication.command_rules", "Command rules"),
  feature("Communication Center", "communication.activity_log", "Activity log"),
  feature("Communication Center", "communication.ai_parser", "AI message interpretation", "monthly"),
  feature("Shed Testing / Lab", "lab.orders", "Create shed test orders", "monthly"),
  feature("Shed Testing / Lab", "lab.labels", "Generate test labels"),
  feature("Shed Testing / Lab", "lab.status_tracking", "Track test status"),
  feature("Shed Testing / Lab", "lab.results", "Upload test results"),
  feature("Shed Testing / Lab", "lab.auto_update_genetics", "Auto-update genetics from result"),
  feature("Shed Testing / Lab", "lab.portal", "Lab portal access"),
  feature("Shed Testing / Lab", "lab.catalog", "Lab catalog access"),
  feature("Shed Testing / Lab", "lab.certificates", "Test certificate storage"),
  feature("Sales", "sales.for_sale", "Mark animals for sale"),
  feature("Sales", "sales.price_animals", "Price animals"),
  feature("Sales", "sales.reservations", "Reservation system"),
  feature("Sales", "sales.buyer_records", "Buyer records"),
  feature("Sales", "sales.history", "Sales history"),
  feature("Sales", "sales.certificates", "Digital certificate of origin"),
  feature("Sales", "sales.invoice_export", "Invoice / receipt export"),
  feature("Sales", "sales.morphmarket_export", "MorphMarket export", "monthly"),
  feature("Sales", "sales.public_catalog", "Public animal catalog"),
  feature("Marketplace", "marketplace.view", "Browse marketplace"),
  feature("Marketplace", "marketplace.favorite", "Favorite listings"),
  feature("Marketplace", "marketplace.contact_seller", "Contact sellers"),
  feature("Marketplace", "marketplace.create_listing", "Create marketplace listings", "count"),
  feature("Marketplace", "marketplace.edit_listing", "Edit marketplace listings"),
  feature("Marketplace", "marketplace.store_page", "Marketplace store page"),
  feature("Marketplace", "marketplace.featured_listing", "Featured listing options"),
  feature("Marketplace", "marketplace.sales_flow", "Marketplace sales flow"),
  feature("Marketplace", "marketplace.reviews", "Marketplace reviews"),
  feature("Marketplace", "marketplace.analytics", "Marketplace analytics"),
  feature("Mobile App", "mobile.scan", "Mobile QR scanning"),
  feature("Mobile App", "mobile.profile", "Mobile animal profile"),
  feature("Mobile App", "mobile.quick_feed", "Mobile feed logging"),
  feature("Mobile App", "mobile.quick_weight", "Mobile weight logging"),
  feature("Mobile App", "mobile.quick_shed", "Mobile shed logging"),
  feature("Mobile App", "mobile.quick_clean", "Mobile cleaning logging"),
  feature("Mobile App", "mobile.quick_water", "Mobile water logging"),
  feature("Mobile App", "mobile.notes", "Mobile notes"),
  feature("Mobile App", "mobile.photos", "Mobile photos"),
  feature("Mobile App", "mobile.tasks", "Mobile daily tasks"),
  feature("Mobile App", "mobile.rack_mode", "Mobile rack workflow"),
  feature("Mobile App", "mobile.communication", "Mobile Communication Center"),
  feature("Mobile App", "mobile.lab", "Mobile lab workflow"),
  feature("Mobile App", "mobile.sales", "Mobile sales workflow"),
  feature("Mobile App", "mobile.offline_sync", "Mobile offline sync"),
  feature("Mobile App", "mobile.team_workflow", "Mobile team workflow"),
  feature("AI Tools", "ai.breeding_advisor", "AI breeding advisor", "monthly"),
  feature("AI Tools", "ai.animal_search", "AI animal search", "monthly"),
  feature("AI Tools", "ai.command_parser", "AI command parser", "monthly"),
  feature("AI Tools", "ai.reports", "AI report generator", "monthly"),
  feature("AI Tools", "ai.health_summary", "AI health note summarizer", "monthly"),
  feature("AI Tools", "ai.sales_writer", "AI sales description writer", "monthly"),
  feature("AI Tools", "ai.social_writer", "AI social media post writer", "monthly"),
  feature("Admin / Team", "team.members", "Team members", "count"),
  feature("Admin / Team", "team.role_permissions", "Role permissions"),
  feature("Admin / Team", "admin.users", "User management"),
  feature("Admin / Team", "admin.tiers", "Subscription management"),
  feature("Admin / Team", "admin.payments", "Payment overview"),
  feature("Admin / Team", "admin.overrides", "Manual user override"),
  feature("Admin / Team", "admin.activity_log", "Admin activity log"),
  feature("Data / Export", "data.csv_export", "CSV export"),
  feature("Data / Export", "data.pdf_export", "PDF export"),
  feature("Data / Export", "data.backup", "Backup"),
  feature("Data / Export", "data.restore", "Restore"),
  feature("Data / Export", "data.api_access", "API access"),
  feature("Data / Export", "data.webhooks", "Webhook access"),
  feature("Data / Export", "data.integrations", "External integrations"),
];

export const LIMIT_FEATURE_KEYS = [
  "animals.create",
  "team.members",
  "spaces.racks",
  "spaces.rooms",
  "animals.photos",
  "animals.documents",
  "qr.pdf_export",
  "communication.telegram_updates",
  "ai.breeding_advisor",
  "lab.orders",
  "sales.morphmarket_export",
  "marketplace.create_listing",
  "mobile.quick_feed",
  "mobile.quick_weight",
  "mobile.quick_shed",
  "mobile.quick_clean",
  "mobile.quick_water",
  "mobile.notes",
  "data.backup",
];

export const FEATURE_GROUPS = Array.from(new Set(FEATURE_CATALOG.map((item) => item.featureGroup)));
