ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'moderator';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'support';

ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "emailVerified" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Profile"
  ADD COLUMN IF NOT EXISTS "profileImageUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "country" TEXT,
  ADD COLUMN IF NOT EXISTS "city" TEXT,
  ADD COLUMN IF NOT EXISTS "language" TEXT,
  ADD COLUMN IF NOT EXISTS "socialLinks" JSONB;
