import speciesIndex from "../config/speciesIndex.json";
import { HttpError } from "../utils/errors";

/**
 * The platform's species taxonomy.
 *
 * Generated by scripts/species/buildSpeciesDatabase.mjs alongside the breeder
 * app's gene tables, so a laboratory can only claim a species that breeders can
 * actually record on an animal. Hand-editing this file's source would let the
 * two drift, which is precisely the bug that made ProHerper's first import match
 * nothing at all.
 */

type SpeciesRow = {
  id: string;
  name: string;
  group: string;
  groupName: string;
  scientificName: string | null;
  reproduction: string;
  traitCount: number;
};

type SpeciesIndexDocument = {
  version: number;
  generatedAt: string;
  source: string;
  groups: Array<{ id: string; name: string; sourceNote: string | null; speciesIds: string[] }>;
  species: SpeciesRow[];
};

const INDEX = speciesIndex as SpeciesIndexDocument;
const BY_ID = new Map(INDEX.species.map((row) => [row.id, row]));

export const listSpecies = () => ({
  version: INDEX.version,
  generatedAt: INDEX.generatedAt,
  groups: INDEX.groups,
  species: INDEX.species,
});

export const isKnownSpecies = (id: unknown): boolean => BY_ID.has(String(id || "").trim());

export const getSpecies = (id: string): SpeciesRow | undefined => BY_ID.get(id);

export const speciesName = (id: string): string => BY_ID.get(id)?.name || id;

/**
 * Validates and de-duplicates a list of species ids.
 *
 * Rejects unknown ids rather than dropping them: silently discarding a species
 * a laboratory believed it had declared would leave it wondering why its tests
 * never reach anyone.
 */
export const normalizeSpeciesIds = (value: unknown, field = "Species"): string[] => {
  if (!Array.isArray(value)) throw new HttpError(400, `${field} must be a list.`);
  const ids = Array.from(
    new Set(value.map((entry) => String(entry || "").trim()).filter(Boolean))
  );
  const unknown = ids.filter((id) => !BY_ID.has(id));
  if (unknown.length) {
    throw new HttpError(400, `Unknown species: ${unknown.join(", ")}.`);
  }
  return ids;
};
